# Generated by Django 5.2.6 on 2025-10-04 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_employee_start_date'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='employees_more',
            field=models.ManyToManyField(blank=True, related_name='assigned_projects', to='employees.employee', verbose_name='Привлечь сотрудников'),
        ),
    ]
