# Generated by Django 5.2.6 on 2025-10-04 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_employee_start_date'),
        ('projects', '0002_project_employees_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='empl_more',
            field=models.ManyToManyField(related_name='projects', through='projects.ProjectEmployee', to='employees.employee'),
        ),
    ]
