# Generated by Django 5.2.6 on 2025-10-04 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_empl_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='empl_more',
        ),
    ]
