# Generated by Django 5.2.6 on 2025-10-05 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_employee_start_date'),
        ('projects', '0004_remove_project_empl_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='new_employees_more',
            field=models.ManyToManyField(blank=True, related_name='new_employees_more', through='projects.ProjectEmployee', to='employees.employee', verbose_name='Привлечь сотрудников'),
        ),
    ]
