# Generated by Django 5.2.6 on 2025-10-18 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_remove_equipment_owner_department_equipment_quantity_and_more'),
        ('projects', '0005_project_new_employees_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectequipment',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.equipmentassignment'),
        ),
    ]
