# Generated by Django 5.2.6 on 2025-10-19 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0006_remove_equipmentassignment_end_date'),
        ('projects', '0006_alter_projectequipment_equipment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectequipment',
            name='equipment',
        ),
        migrations.AddField(
            model_name='projectequipment',
            name='equipment',
            field=models.ManyToManyField(related_name='projects', to='equipment.equipmentassignment'),
        ),
    ]
