# Generated by Django 5.2.6 on 2025-10-20 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0006_remove_equipmentassignment_end_date'),
        ('projects', '0007_remove_projectequipment_equipment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectequipment',
            name='equipment',
            field=models.ManyToManyField(related_name='projects', to='equipment.equipment'),
        ),
    ]
