# Generated by Django 5.2.6 on 2025-10-20 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0006_remove_equipmentassignment_end_date'),
        ('projects', '0008_alter_projectequipment_equipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='equipment_chosen',
            field=models.ManyToManyField(related_name='project_equipment', through='projects.ProjectEquipment', to='equipment.equipment'),
        ),
        migrations.RemoveField(
            model_name='projectequipment',
            name='equipment',
        ),
        migrations.AddField(
            model_name='projectequipment',
            name='equipment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='equipment.equipment'),
            preserve_default=False,
        ),
    ]
