# Generated by Django 5.2.6 on 2025-10-27 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0010_alter_employeeassignment_project'),
        ('projects', '0010_alter_project_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='assignments',
            field=models.ManyToManyField(related_name='assigned_projects_money', through='employees.EmployeeAssignment', to='employees.employee'),
        ),
    ]
