# Generated by Django 5.2.6 on 2025-11-04 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_project_assignments'),
        ('subcontractors', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectemployee',
            options={'verbose_name': 'Сотрудник проекта', 'verbose_name_plural': 'Сотрудники проекта'},
        ),
        migrations.AddField(
            model_name='project',
            name='subcontractors',
            field=models.ManyToManyField(blank=True, related_name='suncontract_projects', through='subcontractors.SubcontractorAssignment', to='subcontractors.subcontractor'),
        ),
    ]
