# Generated by Django 5.2.6 on 2025-11-16 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_alter_projectemployee_options_project_subcontractors'),
        ('subcontractors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='subcontractors',
            field=models.ManyToManyField(blank=True, related_name='subcontract_projects', through='subcontractors.SubcontractorAssignment', to='subcontractors.subcontractor'),
        ),
    ]
