# Generated by Django 5.2.6 on 2025-11-21 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0007_remove_contract_primary_project_contract_projects'),
        ('projects', '0013_alter_project_subcontractors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_projects', to='contracts.contract'),
        ),
    ]
