# Generated by Django 5.2.6 on 2025-11-21 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_alter_project_contract'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='contract',
        ),
    ]
