# Generated by Django 5.2.5 on 2025-09-25 12:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_alter_employee_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата начала работы'),
        ),
    ]
