# Generated by Django 5.2.6 on 2025-10-20 18:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_employee_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='start_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата начала работы'),
        ),
    ]
