# Generated by Django 5.2.6 on 2025-10-27 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_employeeassignment_hourly_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeassignment',
            name='hourly_rate',
        ),
        migrations.AddField(
            model_name='employee',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Часовая ставка'),
        ),
    ]
