# Generated by Django 5.2.6 on 2025-10-27 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_remove_employeeassignment_hourly_rate_and_more'),
        ('projects', '0010_alter_project_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeassignment',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_assignments', to='projects.project'),
        ),
    ]
