# Generated by Django 5.2.6 on 2025-10-08 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='number',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
