# Generated by Django 5.2.6 on 2025-10-12 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_contract_number'),
        ('projects', '0005_project_new_employees_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='project_more',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='projects.project'),
            preserve_default=False,
        ),
    ]
