# Generated by Django 5.2.6 on 2025-11-16 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0004_alter_contract_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='project_more',
        ),
    ]
