# Generated by Django 5.2.6 on 2025-11-16 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0005_remove_contract_project_more'),
        ('projects', '0013_alter_project_subcontractors'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='primary_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_contract', to='projects.project', verbose_name='Основной проект'),
        ),
    ]
