# Generated by Django 5.2.6 on 2025-11-21 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0006_contract_primary_project'),
        ('projects', '0013_alter_project_subcontractors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='primary_project',
        ),
        migrations.AddField(
            model_name='contract',
            name='projects',
            field=models.ManyToManyField(blank=True, related_name='contracts', to='projects.project', verbose_name='Проекты по договору'),
        ),
    ]
