# Generated by Django 5.2.5 on 2025-09-23 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        ('employees', '0002_remove_employee_position_alter_employee_birth_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Должность')),
                ('is_head', models.BooleanField(default=False, verbose_name='Начальник')),
            ],
        ),
        migrations.CreateModel(
            name='AutomationEngineer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departments.department')),
                ('full_name', models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.CASCADE, related_name='employee_avt_eng', to='employees.employee', verbose_name='ФИО')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='avtomatizations.automationrole', verbose_name='Должность')),
            ],
        ),
        migrations.CreateModel(
            name='AutomationDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departments.department', verbose_name='Название отдела')),
                ('workers', models.ManyToManyField(related_name='automation_departments', to='avtomatizations.automationengineer', verbose_name='Сотрудники')),
            ],
        ),
    ]
