# Generated by Django 5.2.5 on 2025-09-23 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avtomatizations', '0001_initial'),
        ('employees', '0003_alter_employee_birth_date'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='automationengineer',
            name='birth_date',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='birth_date_avt_eng', to='employees.employee', verbose_name='Дата рождения'),
        ),
        migrations.AddField(
            model_name='automationengineer',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='engineers/'),
        ),
        migrations.AddField(
            model_name='automationengineer',
            name='projects',
            field=models.ManyToManyField(related_name='engineers', to='projects.project', verbose_name='Проекты'),
        ),
    ]
