# Generated by Django 5.2.5 on 2025-09-24 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avtomatizations', '0002_automationengineer_birth_date_and_more'),
        ('employees', '0003_alter_employee_birth_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='automationengineer',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='automationengineer',
            name='full_name',
        ),
        migrations.AddField(
            model_name='automationengineer',
            name='worker_avt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.employee', verbose_name='Сотрудник'),
        ),
    ]
