# Generated by Django 5.2.5 on 2025-09-26 07:38

import avtomatizations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avtomatizations', '0003_remove_automationengineer_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automationengineer',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name=avtomatizations.models.engineer_photo_path),
        ),
    ]
