# Generated by Django 5.2.6 on 2025-09-28 18:54

import avtomatizations.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avtomatizations', '0004_alter_automationengineer_photo'),
        ('departments', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automationengineer',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departments.department', verbose_name='Отдел'),
        ),
        migrations.AlterField(
            model_name='automationengineer',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=avtomatizations.models.engineer_photo_path),
        ),
        migrations.AlterField(
            model_name='automationengineer',
            name='projects',
            field=models.ManyToManyField(blank=True, related_name='engineers', to='projects.project', verbose_name='Проекты'),
        ),
    ]
