# Generated by Django 5.2.6 on 2025-10-18 17:16
from datetime import date

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_remove_equipment_owner_department_equipment_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentassignment',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipmentassignment',
            name='start_date',
            field=models.DateField(default=date.today),
            preserve_default=False,
        ),
    ]
