# Generated by Django 5.2.6 on 2025-10-18 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0003_equipmentassignment_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentassignment',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='equipment.equipment'),
        ),
    ]
