# Generated by Django 5.2.6 on 2025-10-18 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0004_alter_equipmentassignment_equipment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipmentassignment',
            name='start_date',
        ),
    ]
