# Generated by Django 5.2.6 on 2025-10-19 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0005_remove_equipmentassignment_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipmentassignment',
            name='end_date',
        ),
    ]
