# Generated by Django 5.2.6 on 2025-10-21 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0006_remove_equipmentassignment_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentassignment',
            name='assigned_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
