# Generated by Django 5.2.6 on 2025-10-21 13:46
from datetime import date

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0007_alter_equipmentassignment_assigned_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentassignment',
            name='assigned_date',
            field=models.DateField(default=date.today),
            preserve_default=False,
        ),
    ]
