# Generated by Django 5.2.6 on 2025-10-21 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0008_alter_equipmentassignment_assigned_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipmentassignment',
            name='assigned_date',
        ),
        migrations.RemoveField(
            model_name='equipmentassignment',
            name='returned_date',
        ),
    ]
