# Generated by Django 5.2.6 on 2025-10-21 19:14
from datetime import date

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0009_remove_equipmentassignment_assigned_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentassignment',
            name='assigned_date',
            field=models.DateField(default=date.today),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipmentassignment',
            name='returned_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
