# Generated by Django 5.2.6 on 2025-11-22 17:56

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0010_equipmentassignment_assigned_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_department', models.CharField(max_length=100, verbose_name='Отдел-отправитель')),
                ('to_department', models.CharField(max_length=100, verbose_name='Отдел-получатель')),
                ('transfer_date', models.DateField(default=datetime.date.today, verbose_name='Дата передачи')),
                ('responsible_person', models.CharField(max_length=255, verbose_name='Ответственное лицо')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Комментарии')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='equipment.equipment', verbose_name='Оборудование')),
            ],
            options={
                'verbose_name': 'Передача оборудования',
                'verbose_name_plural': 'Передачи оборудования',
                'ordering': ['-transfer_date'],
            },
        ),
    ]
