# Generated by Django 5.2.6 on 2025-11-22 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
        ('equipment', '0011_equipmenttransfer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipment',
            options={'verbose_name': 'Оборудование', 'verbose_name_plural': 'Оборудование'},
        ),
        migrations.AddField(
            model_name='equipment',
            name='condition',
            field=models.CharField(choices=[('good', 'Исправно'), ('repair', 'Требует ремонта'), ('broken', 'Вышло из строя')], default='good', max_length=50, verbose_name='Состояние'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Стоимость'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='current_department',
            field=models.ForeignKey(blank=True, help_text='Отдел, который сейчас использует оборудование', null=True, on_delete=django.db.models.deletion.SET_NULL, to='departments.department', verbose_name='Текущий отдел'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Примечания'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='purchase_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата покупки'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='serial_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Серийный номер'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='status',
            field=models.CharField(choices=[('in_stock', 'На складе'), ('in_use', 'В использовании'), ('in_repair', 'В ремонте')], default='in_stock', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='equipmenttransfer',
            name='from_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_sent', to='departments.department', verbose_name='Отдел-отправитель'),
        ),
        migrations.AlterField(
            model_name='equipmenttransfer',
            name='to_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_received', to='departments.department', verbose_name='Отдел-получатель'),
        ),
    ]
