# Generated by Django 5.2.6 on 2025-11-22 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0010_alter_employeeassignment_project'),
        ('equipment', '0012_alter_equipment_options_equipment_condition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmenttransfer',
            name='responsible_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee', verbose_name='Ответственное лицо'),
        ),
    ]
