# Generated by Django 5.2.6 on 2025-09-29 08:40

import constructors.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        ('employees', '0004_employee_start_date'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConstructorRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Должность')),
                ('is_head', models.BooleanField(default=False, verbose_name='Начальник')),
            ],
        ),
        migrations.CreateModel(
            name='Constructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=constructors.models.engineer_constr_photo_path)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='departments.department', verbose_name='Отдел')),
                ('projects', models.ManyToManyField(blank=True, related_name='constructors', to='projects.project', verbose_name='Проекты')),
                ('worker_constr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.employee', verbose_name='Сотрудник')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructors.constructorrole', verbose_name='Должность')),
            ],
        ),
        migrations.CreateModel(
            name='ConstrDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название отдела')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('workers', models.ManyToManyField(related_name='design_departments', to='constructors.constructor', verbose_name='Сотрудники')),
            ],
        ),
    ]
