# Generated by Django 5.2.6 on 2025-11-21 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='constructor',
            name='certificates',
            field=models.TextField(blank=True, help_text='Перечислите авторские свидетельства, патенты, изобретения', null=True, verbose_name='Авторские свидетельства'),
        ),
    ]
