# Generated by Django 5.2.6 on 2025-11-22 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructors', '0002_constructor_certificates'),
    ]

    operations = [
        migrations.AddField(
            model_name='constructor',
            name='patent_count',
            field=models.PositiveIntegerField(default=0, help_text='Введите число — сколько патентов или свидетельств у конструктора', verbose_name='Количество авторских свидетельств'),
        ),
    ]
